[package]
name = "pwmp-types"
version = "1.0.7"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
bincode = "1.3.3"
rust_decimal = { version = "1.33.1", features = ["serde-bincode"] }
rust_decimal_macros = { version = "1.33.1", features = ["reexportable"] }
