[package]
name = "pwmp-types"
version = "0.1.0"
edition = "2021"

[features]
default = []

bigdecimal = ["dep:bigdecimal"]

[dependencies]
bigdecimal = { version = "0.3.1", features = ["serde"], optional = true }
serde = { version = "1.0.193", features = ["derive"] }
serde_cbor = "0.11.2"
