[package]
name = "pwmp-types"
version = "1.0.0"
edition = "2021"

[dependencies]
bigdecimal = { version = "0.3.1", features = ["serde"] }
serde = { version = "1.0.193", features = ["derive"] }
bincode = "1.3.3"
